In [1]:
import numpy as np

# np.array()
arr1 = np.array([1, 2, 3])
print("np.array():", arr1)

# np.zeros()
zeros_array = np.zeros((2, 3))
print("np.zeros():\n", zeros_array)

# np.ones()
ones_array = np.ones((3, 2))
print("np.ones():\n", ones_array)

# np.reshape()
arr2 = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr2, (2, 3))
print("np.reshape():\n", reshaped_arr)

# np.concatenate()
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6]])
concatenated_arr = np.concatenate((arr3, arr4), axis=0)
print("np.concatenate():\n", concatenated_arr)

# np.mean()
arr5 = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr5)
print("np.mean():", mean_value)

# np.sum()
arr6 = np.array([1, 2, 3, 4, 5])
sum_value = np.sum(arr6)
print("np.sum():", sum_value)

# np.min()
arr7 = np.array([3, 1, 4, 1, 5, 9, 2])
min_value = np.min(arr7)
print("np.min():", min_value)

# np.max()
arr8 = np.array([3, 1, 4, 1, 5, 9, 2])
max_value = np.max(arr8)
print("np.max():", max_value)

# np.argmax()
index_of_max = np.argmax(arr8)
print("np.argmax():", index_of_max)

# np.argmin()
index_of_min = np.argmin(arr8)
print("np.argmin():", index_of_min)

# np.random.rand()
random_array = np.random.rand(2, 3)
print("np.random.rand():\n", random_array)

# np.random.randn()
random_normal_array = np.random.randn(2, 3)
print("np.random.randn():\n", random_normal_array)

# np.random.randint()
random_int = np.random.randint(1, 10, size=(2, 3))
print("np.random.randint():\n", random_int)

# np.dot()
dot_product = np.dot(arr3, arr4.T)
print("np.dot():\n", dot_product)


np.array(): [1 2 3]
np.zeros():
 [[0. 0. 0.]
 [0. 0. 0.]]
np.ones():
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
np.reshape():
 [[1 2 3]
 [4 5 6]]
np.concatenate():
 [[1 2]
 [3 4]
 [5 6]]
np.mean(): 3.0
np.sum(): 15
np.min(): 1
np.max(): 9
np.argmax(): 5
np.argmin(): 1
np.random.rand():
 [[0.29613498 0.30394218 0.9643949 ]
 [0.38740916 0.8339097  0.87004792]]
np.random.randn():
 [[-0.8264917   1.35510747  0.34040968]
 [ 0.18934387 -0.5204021  -0.29515981]]
np.random.randint():
 [[3 8 2]
 [9 8 1]]
np.dot():
 [[17]
 [39]]
